name: Deploy Pre-Built Frontend
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate dist folder
        run: |
          if [ ! -d "dist" ]; then
            echo "❌ Error: dist folder not found!"
            ls -la
            exit 1
          fi
          echo "✔ dist folder exists with contents:"
          ls -la dist/

      - name: Deploy files
        run: |
          echo "Deploying files to /var/www/frontend..."
          sudo rm -rf /var/www/frontend/*
          sudo cp -r dist/* /var/www/frontend/
          sudo chown -R www-data:www-data /var/www/frontend
          echo "✔ Files deployed successfully"

      - name: Restart Nginx
        run: |
          echo "Restarting Nginx..."
          sudo systemctl restart nginx
          echo "✔ Nginx restarted"
